name: release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Build And Deploy On Tencent Cloud
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.DEPLOY_HOST }}
      SERVER_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
      SERVER_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      DEPLOY_BRANCH: main

    steps:
      - name: Deploy on cloud server
        if: ${{ env.SERVER_HOST != '' && env.SERVER_USERNAME != '' && env.SERVER_PASSWORD != '' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          password: ${{ env.SERVER_PASSWORD }}
          script: |
            set -e
            
            REPO_DIR=~/TimeCampus-Portal
            REPO_URL=https://github.com/BUAA2026SE-404NotFound/TimeCampus-Portal.git
            APP_DIR=/var/www/timecampus/portal
            if [ ! -d "$REPO_DIR" ]; then
              git clone $REPO_URL $REPO_DIR
            fi
            cd $REPO_DIR
            git checkout ${{ env.DEPLOY_BRANCH }}
            git pull origin ${{ env.DEPLOY_BRANCH }}
            
            if [ ! command -v pnpm &> /dev/null ]; then
              exit 1
            fi
            
            # 构建项目
            pnpm install
            # 构建项目（超时 30s 直接失败）
            if ! timeout 30s pnpm run build; then
              echo "Build timed out after 30 seconds"
              exit 1
            fi

            # 将构建产物复制到部署目录
            rm -rf $APP_DIR/*
            cp -r dist/* $APP_DIR/
            
            echo "Deployment completed successfully!"
